### ISSUE TITLE
{key,value}Encoding

### ISSUE THREAD

**Issue by dstokes** [FrozenRidge/level-userdb#2]
I have a leveldb instance exposed over `multilevel` that doesn't specify key / value encodings in favor of allowing clients to configure their reads / writes. Unfortunately, there's no way to set these values when using `level-userdb`'s `addUser` and `findUser` which means everything ends up as `'[object Object]'`.

Any chance this module could support the `put` / `get` options object while also supporting the user `data` parameter? I'd be more than happy to open a PR if it's within the scope of the project.

**Comment by tphummel** [comment]
:+1:

**Comment by niallo** [comment]
Open to PR, sure!

On Monday, April 14, 2014, Drew Stokes notifications@github.com wrote:

> I have a leveldb instance exposed over multilevel that doesn't specify
> key / value encodings in favor of allowing clients to configure their reads
> / writes. Unfortunately, there's no way to set these values when using
> level-userdb's addUser and findUser which means everything ends up as '[object
> Object]'.
> 
> Any chance this module could support the put / get options object while
> also supporting the user data parameter? I'd be more than happy to open a
> PR if it's within the scope of the project.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/FrozenRidge/level-userdb/issues/2
> .

## 

Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by dstokes** [comment]
opened https://github.com/FrozenRidge/level-userdb/pull/3/files
